name: 'Composite action'
description: 'A composite action to set up Node.js, install dependencies, and run unit tests'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
    default: '20.x'
  work-dir:
    description: 'Working directory for the action'
    required: false
    default: 'my-app'
  
runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      shell: bash

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
      shell: bash

    - name: Install Dependencies
      run: npm ci
      shell: bash

    - name: Run Unit Tests
      run: npm run test
      shell: bash