name: Using Actions
on: 
  workflow_dispatch:
env:
  WORK_DIR: my-app
  NODE_VERSION: 20.x

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.WORK_DIR}}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: composite-actions
        uses: ./.github/actions/composite-deps@v1 
        with:
          node-version: ${{env.NODE_VERSION}}
          work-dir: ${{env.WORK_DIR}}